### ISSUE TITLE
Compare GeoTopicParser vs Geograpy + GeoPy

### ISSUE THREAD

**Issue by MBoustani** [memex-explorer/GeoParser#12]
Here we are going to compare GeoTopicParser with Geograpy combined with GeoPy ruing over same text document.
@smadha can you please take over GeoTopicParser [1](https://wiki.apache.org/tika/GeoTopicParser) and print the result here.
I am going to use Geograpy + GeoPy over same text and print the result here [2](https://github.com/geopy/geopy)

Files:

[TAP1500-Active-Probe-Datasheet-6.pdf](https://github.com/MBoustani/GeoParser/files/4451/TAP1500-Active-Probe-Datasheet-6.pdf)
[5c0024-25.pdf](https://github.com/MBoustani/GeoParser/files/4452/5c0024-25.pdf)

**Comment by smadha** [comment]
5c0024-25.pdf:

Content-Length: 5424
Content-Type: application/geotopic
Geographic_LATITUDE: 52.00007
Geographic_LONGITUDE: -106.1679
**Geographic_NAME: 
Optional_LATITUDE1: 16.10667
Optional_LONGITUDE1: -93.34028
Optional_NAME1: Australia**
X-Parsed-By: org.apache.tika.parser.DefaultParser
X-Parsed-By: org.apache.tika.parser.geo.topic.GeoParser
resourceName: 5c0024-25.geot

_NAME1 says Australia but coordinates point Mexico_

**Comment by smadha** [comment]
TAP1500-Active-Probe-Datasheet-6.pdf

Content-Length: 6443
Content-Type: application/geotopic
Geographic_LATITUDE: -31.3096
Geographic_LONGITUDE: 18.357
Geographic_NAME: South Africa
**Optional_LATITUDE1: 33.52188**
Optional_LATITUDE10: 16.43083
Optional_LATITUDE11: -30.77313
Optional_LATITUDE12: 24.45697
Optional_LATITUDE13: -37.1525
**Optional_LATITUDE14: 24.48361**
**Optional_LATITUDE15: 58.57514**
Optional_LATITUDE16: -31.95194
Optional_LATITUDE17: -33.8485
Optional_LATITUDE18: 33.51873
Optional_LATITUDE19: 43.17646
Optional_LATITUDE2: 22.95805
Optional_LATITUDE20: 1.63414
Optional_LATITUDE21: 52.3471
Optional_LATITUDE22: 25.69997
Optional_LATITUDE23: 42.69139
Optional_LATITUDE24: -8.0599
Optional_LATITUDE3: 7.06977
Optional_LATITUDE4: 43.20978
Optional_LATITUDE5: 59.47263
Optional_LATITUDE6: 24.32972
Optional_LATITUDE7: 45.70301
Optional_LATITUDE8: -20.18754
Optional_LATITUDE9: 23.1168
**Optional_LONGITUDE1: 36.28219**
Optional_LONGITUDE10: -93.33167
Optional_LONGITUDE11: 149.79761
Optional_LONGITUDE12: 54.36648
Optional_LONGITUDE13: 145.41962
**Optional_LONGITUDE14: 54.35103**
**Optional_LONGITUDE15: 5.75946**
Optional_LONGITUDE16: 115.8728
Optional_LONGITUDE17: 151.11791
Optional_LONGITUDE18: 36.28726
Optional_LONGITUDE19: -76.27465
Optional_LONGITUDE2: -109.93898
Optional_LONGITUDE20: -75.5719
Optional_LONGITUDE21: 24.3085
Optional_LONGITUDE22: -99.23454
Optional_LONGITUDE23: 19.71167
Optional_LONGITUDE24: 112.0284
Optional_LONGITUDE3: 125.60859
Optional_LONGITUDE4: -77.69306
Optional_LONGITUDE5: 11.1623
Optional_LONGITUDE6: -107.00836
Optional_LONGITUDE7: -97.78594
Optional_LONGITUDE8: 28.27407
Optional_LONGITUDE9: -82.38859
**Optional_NAME1: Netherlands**
Optional_NAME10: Austria
Optional_NAME11: Korea
Optional_NAME12: Italy
Optional_NAME13: Switzerland
**Optional_NAME14: United Kingdom**
**Optional_NAME15: India**
Optional_NAME16: Central TAFE East Perth
Optional_NAME17: France Bay
Optional_NAME18: Poland
Optional_NAME19: Belgium
Optional_NAME2: Hong Kong
Optional_NAME20: Brazil
Optional_NAME21: Germany
Optional_NAME22: China
Optional_NAME23: Japan
Optional_NAME24: Sweden
Optional_NAME3: People's Park
Optional_NAME4: Greece
Optional_NAME5: Finland
Optional_NAME6: El Africa
Optional_NAME7: Spain
Optional_NAME8: Ireland
Optional_NAME9: Caribbean
X-Parsed-By: org.apache.tika.parser.DefaultParser
X-Parsed-By: org.apache.tika.parser.geo.topic.GeoParser
resourceName: TAP1500-Active-Probe-Datasheet-6.geot

_NAME15 says India but coordinates 58.57514,5.75946 point Norway
NAME1 says Netherlands but coordinates 33.52188,36.28219 point Syria
NAME14: United Kingdom but coordinates 24.48361,54.35103 point UAE_

Below is a fusion doc for all the locations. Markers are populated using lat,long from above response and if you click on any marker it will give location reported in above.

https://www.google.com/fusiontables/data?docid=1bDk4hGSE5VbSxYflH7oq2cj86te3oeoHa8w3L0X_#map:id=3

**Comment by smadha** [comment]
Content-Length: 164
Content-Type: application/geotopic
**Geographic_LATITUDE: -34.96862
Geographic_LONGITUDE: 139.18517
Geographic_NAME: Phoenix**
X-Parsed-By: org.apache.tika.parser.DefaultParser
X-Parsed-By: org.apache.tika.parser.geo.topic.GeoParser
resourceName: f0034223fe94a260ae43c32764e81358 EnlargeImageoid=32732460 image=.geot

_Location reported: Phoenix but coordinates point Australia_

*_Phoenix is correctly recognized by GeoTopicParser but if I change it to phoenix it does not reports anything *_

[f0034223fe94a260ae43c32764e81358 EnlargeImageoid=32732460 image=.txt](https://github.com/MBoustani/GeoParser/files/4620/f0034223fe94a260ae43c32764e81358.EnlargeImageoid.32732460.image.txt)
