### ISSUE TITLE
Upload file to server using Girder

### ISSUE THREAD

**Issue by MBoustani** [memex-explorer/GeoParser#14]
As we are replacing current CherryPy serve to Girder, we need to define a REST URL to POST uploaded file to Girder Filesystem

**Comment by danlamanna** [comment]
Note, if you're going to be using girder-client - a similar example of this exists [here](https://github.com/Kitware/minerva/blob/7d6cc432a2226de7277b622382cd0d4687e102cd/analyses/NEX/geo_js_contour/contour.py#L86-L91), and those methods are well documented [here](http://girder.readthedocs.org/en/latest/python-client.html#girder_client.GirderClient.addMetadataToFolder).

**Comment by chrismattmann** [comment]
Thanks dan

**Comment by MBoustani** [comment]
Thanks Dan.
I created a separate Issue (https://github.com/MBoustani/GeoParser/issues/16) for it.

**Comment by smadha** [comment]
File upload API of girder is directly called from front end now. Related issue https://github.com/MBoustani/GeoParser/issues/22

**Comment by MBoustani** [comment]
Server changed to Django. Going to open new issue for upload file using Django.
