### ISSUE TITLE
Front-end create item for each file within existing folder and upload file in that item

### ISSUE THREAD

**Issue by MBoustani** [memex-explorer/GeoParser#22]
We have already made collection and a folder called "uploaded_files" within collection.
As user upload a file, client can create and item with in "uploaded_files" using Girder REST API.

@smadha please review Grider docs REST API to see how you can create item with in folder.

**Comment by smadha** [comment]
Decided to use below set of APIs to upload the files:
1. GET folder ID - /api/v1/./folder?parentType=collection&text=uploaded_files
2. POST new Item - /api/v1/./item?folderId=<from step 1>&name=<file_name>&description=<file_name>
3. POST new file - /api/v1/./file?parent

**Comment by smadha** [comment]
This also fixes : https://github.com/MBoustani/GeoParser/issues/14

**Comment by smadha** [comment]
1. Setup Girder using admin girder:girder
2. Have to create a asset store in Girder for files to be uploaded
   https://github.com/girder/girder/issues/67
3. Follow https://github.com/MBoustani/GeoParser/issues/25 to setup static files
