### ISSUE TITLE
Merging CherryPy webserver with Girder

### ISSUE THREAD

**Issue by MBoustani** [memex-explorer/GeoParser#25]
GeoParser at this stage is using two servers as backend.
1- CherryPy as web server
2- Grider for file system and running jobs

Beside running two servers at same time could increase the chance of application failure there is problem if calling Girder on different port by CherryPy in different port (cross-domain issue), therefore these two can be merged to one and have Girder take care of everything.

**Comment by smadha** [comment]
Steps to merge(Till today, might be simplified later)
1. Create sym link to https://github.com/MBoustani/GeoParser/tree/master/plugin/geoparser_plugin in girder installation -> /path/to/installation/python2.7/site-packages/girder/plugins/.
2. Create sym link to  GeoParser/static/\* content in /path/to/installation/python2.7/site-packages/girder/clients/web/static
3. Enable GeoParser plugin from Girder GUI.

After this GeoParser will start getting served from root and girder will be on /girder. Only issue left is that girder does not points to correct static files any more. We need to modify below files to correct files path in girder. Adding "/" at start of all css,js will fix.

/path/to/installation/python2.7/site-packages/girder/utility/webroot.py
/path/to/installation/python2.7/site-packages/girder/api/describe.py

**Comment by smadha** [comment]
Need to add an asset store to start uploading file:
https://github.com/girder/girder/issues/67

**Comment by MBoustani** [comment]
Server changed to Django
