### ISSUE TITLE
Mock REST services

### ISSUE THREAD

**Issue by smadha** [memex-explorer/GeoParser#3]
Below APIs need to be mocked

[API signature], [Method],
[Sample Response]
1.  /upload  POST
   Response code - 200
2. /status/%file_id% GET
   {
   "name":"File Name",
   "status":"Message to be displayed to user",
   "stepCount":4,
   "parsedInfo":[
   {
   "lat":-34.6037232,
   "lon":-58.3815931,
   "name":"Aires Argentina",
   "refCount":10,
   "refContext":"Test line 4 in file uploaded",
   "refUrl":"https://geo1.ggpht.com/cbk?panoid=wkEz-Hwmc44EnMsE7SuXBw&output=thumbnail"
   },
   {
   "lat":19.4302678,
   "lon":-99.1373136,
   "name":"Mexico City, Mexico",
   "refCount":2,
   "refContext":"Test line 42 in file uploaded",
   "refUrl":"https://geo0.ggpht.com/cbk?output=thumbnail&thumb=2&panoid=3DKyddof6dWPw3tx5BULbQ&w=96&h=64&yaw=176"
   }
   ]
   }
3. /search/index/%keyword%  GET
   {
   "name":"File Name",
   "status":"Message to be displayed to user",
   "stepCount":4,
   "parsedInfo":[
   {
   "lat":-34.6037232,
   "lon":-58.3815931,
   "name":"Aires Argentina",
   "refCount":10,
   "refContext":"Test line 4 in file uploaded",
   "refUrl":"https://geo1.ggpht.com/cbk?panoid=wkEz-Hwmc44EnMsE7SuXBw&output=thumbnail"
   },
   {
   "lat":19.4302678,
   "lon":-99.1373136,
   "name":"Mexico City, Mexico",
   "refCount":2,
   "refContext":"Test line 42 in file uploaded",
   "refUrl":"https://geo0.ggpht.com/cbk?output=thumbnail&thumb=2&panoid=3DKyddof6dWPw3tx5BULbQ&w=96&h=64&yaw=176"
   }
   ]
   }

https://drive.google.com/open?id=1ASR0j0lzT8GqifZ0ep6WMBV9SaAOENPHUIqUrrR7dbo

**Comment by MBoustani** [comment]
https://github.com/MBoustani/GeoParser/issues/4 for upload file.

**Comment by MBoustani** [comment]
@smadha please do a git pull, I have added GET for status and search.
