### ISSUE TITLE
Issue with indexing extracted text from Tika to Solr

### ISSUE THREAD

**Issue by MBoustani** [memex-explorer/GeoParser#33]
Some text return from Tika has some characters that cannot be indexed to Solr.

**Comment by smadha** [comment]
I also faced it sometime back. I was able to fix it by using " -T  or --text-main     Output plain text content (main content only) " on CLI. Might be the same issue

**Comment by MBoustani** [comment]
@smadha are we facing this issue anymore, or it got fixed by adding "-T" ?

**Comment by smadha** [comment]
@MBoustani I believe this should be fixed now. I was not able to use "-T" option through Tika server but I simplified text before passing it to Tika and I didn't saw this problem again. 

I am closing it for now, if issue reoccurs we can open it and investigate
