### ISSUE TITLE
Support Crawled indexed data

### ISSUE THREAD

**Issue by MBoustani** [memex-explorer/GeoParser#40]
Usually crawled data are being indexed to either Solr or Elasticsearch.
GeoParser should be able to get the URL to either of these to indexing machines and domain name, scan whole indexes and geoparse them.
The result (location name and point) will be stored in Solr internally along side with path to crawled data.

**Comment by smadha** [comment]
@MBoustani should we handle use case like user adding different indexes on same domain name?
