### ISSUE TITLE
Update menu for crawled data input

### ISSUE THREAD

**Issue by MBoustani** [memex-explorer/GeoParser#41]
@smadha Please update the menu as below:
<img width="450" alt="screen shot 2015-11-16 at 3 33 17 pm" src="https://cloud.githubusercontent.com/assets/5606458/11198243/2c363658-8c78-11e5-909a-9c3b41ce322c.png">

**Comment by smadha** [comment]
![screen shot 2015-11-21 at 18 48 20](https://cloud.githubusercontent.com/assets/14187172/11321770/7947ff10-9080-11e5-86d6-f79ec2e4067b.png)

@lawongsta Looks fine?
