### ISSUE TITLE
updated return_points url

### ISSUE THREAD

**Issue by MBoustani** [memex-explorer/GeoParser#42]
@smadha I have update the "return_points" url to work with both uploaded files and crawled data.
Now you can call return_points to get point from both.
However, you need to update the code you have now that called return_points, here is the update:

For uploaded files: http://localhost:8000/return_points/<file_name>/uploaded_files
Example: http://localhost:8000/return_points/5c0024-25.pdf/uploaded_files

For crawled data: http://localhost:8000/return_points/<solr_url>/<core_name>
Example: http://localhost:8000/return_points/http://crawl.dyndns.org/solr/domain

Please update both.

**Comment by smadha** [comment]
@MBoustani  for crawled data shouldn't it be just domain name? 
Example: http://localhost:8000/return_points/domain

**Comment by MBoustani** [comment]
@smadha for now lets return point based on both domain and solr_ulr, because just based on domain may return a lot of point and hard to show, so go with this format:

For crawled data: http://localhost:8000/return_points//
Example: http://localhost:8000/return_points/http://crawl.dyndns.org/solr/domain

**Comment by smadha** [comment]
@MBoustani @lawongsta - I suggest we should discuss flow for showing indexed data on UI. As of now I have used search index box to visualize indexed data using below steps.

Save Index - 
1. Index URL - http://crawl.dyndns.org/solr/materials_research_v2
2. Domain - materials_research

Search Index
1.   Fill text box with - http://crawl.dyndns.org/solr/materials_research_v2/materials_research
2.   Click on search icon to visualize points on map.

But this should be changed.

any ideas?
