### ISSUE TITLE
Show list of indexed geoparsed under "save" button

### ISSUE THREAD

**Issue by MBoustani** [memex-explorer/GeoParser#45]
After user types domain name and indexed URL put the result under save button that user can come back and on/off point on map.

**Comment by smadha** [comment]
To clarify this will need new APIs to fetch list of available domains and list of indexed URLs. I will keep this issue updated on APIs status.

**Comment by MBoustani** [comment]
@smadha you can call "list_of_domains" to get the list of domains if exists.

Example: `http://localhost:8000/list_of_domains`

**Comment by smadha** [comment]
@MBoustani Thanks! I will use it. Is there a separate API for getting geotagged index under that domain?

**Comment by MBoustani** [comment]
@smadha you mean to get the crawled URLs under each domain?
Lets just list domains for now and have checkbox beside it for toggling on/off points on map.

**Comment by MBoustani** [comment]
@smadha calling `http://localhost:8000/list_of_domains` returns:
`{u'mr': [u'http://crawl.dyndns.org/solr/materials_research_v2']}`
"mr" is domain name with list of all urls under domain name.

**Comment by MBoustani** [comment]
You did commit to master branch and not the new one I created.
But now I have moved using_geotopicparser to master and master to using_geograpy_geopy.
So can you please git pull fresh and commit changes of #45 again on new master

Thanks
Mazi

**Comment by smadha** [comment]
Done!
