### ISSUE TITLE
Show more meta data on popups and link back to solr doc

### ISSUE THREAD

**Issue by smadha** [memex-explorer/GeoParser#52]
Need to show more data on popups to analyze individual bubble.
- "title" : "Title of doc fetched as configured",
- "descr" : "Short description fetched as per configuration"
- "url" : "Link to html/image"
- "solr_url" : "Link to solr_doc"

**Comment by smadha** [comment]
![screen shot 2016-03-17 at 18 46 42](https://cloud.githubusercontent.com/assets/14187172/13866254/ab673046-ec70-11e5-98ae-62f3bdc607ff.png)

**Comment by chrismattmann** [comment]
LOVE

**Comment by chrismattmann** [comment]
@smadha

**Comment by smadha** [comment]
Closing. More progress update on #55
