### ISSUE TITLE
Make installation easier

### ISSUE THREAD

**Issue by smadha** [memex-explorer/GeoParser#54]
1. Commit l-g-g jar from maven central. https://oss.sonatype.org/content/groups/public/edu/usc/ir/lucene-geo-gazetteer/0.2/lucene-geo-gazetteer-0.2-jar-with-dependencies.jar
2. Commit tika-server jar from mirror. http://www-us.apache.org/dist/tika/tika-server-1.12.jar

Start solr,l-g-g,tika geotopic server through `manage.py`

@MBoustani @chrismattmann any thoughts on this?

**Comment by MBoustani** [comment]
@smadha I am currently working on using Docker.

**Comment by smadha** [comment]
What will be our approach for installing tika and lucene-geo-gazetteer? Are we committing jar files into repo or will we be downloading them from mirror while installing?

I think we should also look for integrating geotopic parser with tika-python. Like not through a separate instance of tika-server (like we do now), but forming a separate object of tika-python which can directly parse using geotopic parser instead of default parser. I think we will need to append some files in class path and then we should be good. 

@chrismattmann - thoughts?

**Comment by chrismattmann** [comment]
Use pip for Tika and use maven for lgg

**Comment by MBoustani** [comment]
@smadha @chrismattmann I have both these steps along with other steps in Dockerfile, still testing and would be out soon.

**Comment by smadha** [comment]
@chrismattmann I was suggesting to use tika python with location-ner-model , geotopic-mime in tika-server classpath.

**Comment by MBoustani** [comment]
@chrismattmann @smadha 
Here is my dockefile content, all steps go fine except last line I'm getting the error

```
#FROM debian:jessie
FROM ubuntu:14.04
#RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN apt-get update && apt-get install -y \
    openjdk-7-jdk \
    curl \
    git \
    libxml2-dev \
    python \
    build-essential \
    python-dev \
    python-pip \
    python-numpy \
    python-scipy \
    maven

ENV JAVA_HOME /usr/lib/jvm/java-7-openjdk-amd64/jre/
ENV PATH $JAVA_HOME:$PATH

RUN echo $PATH
RUN echo $JAVA_HOME


RUN git clone https://github.com/chrismattmann/lucene-geo-gazetteer.git
ENV LGG /lucene-geo-gazetteer/src/main/bin/
ENV PATH $LGG:$PATH

WORKDIR lucene-geo-gazetteer
RUN mvn install assembly:assembly -DskipTests

RUN mkdir -p location-ner-model
WORKDIR location-ner-model
RUN curl -O http://opennlp.sourceforge.net/models-1.5/en-ner-location.bin
RUN mkdir -p org/apache/tika/parser/geo/topic
RUN mv en-ner-location.bin org/apache/tika/parser/geo/topic

WORKDIR /lucene-geo-gazetteer

RUN mkdir -p geotopic-mime
WORKDIR  geotopic-mime
RUN curl -O https://raw.githubusercontent.com/chrismattmann/geotopicparser-utils/master/mime/org/apache/tika/mime/custom-mimetypes.xml
RUN mkdir -p org/apache/tika/mime
RUN mv custom-mimetypes.xml org/apache/tika/mime

WORKDIR /lucene-geo-gazetteer

RUN curl -O http://download.geonames.org/export/dump/allCountries.zip
RUN unzip allCountries.zip
RUN mkdir -p geoIndex
RUN ["/bin/bash", "-c", "lucene-geo-gazetteer -i geoIndex -b allCountries.txt"]

```

Error: 

```
WARNING: Building Finished
Sub command not recognised
The command '/bin/bash -c lucene-geo-gazetteer -i geoIndex -b allCountries.txt' returned a non-zero code: 255
```

**Comment by MBoustani** [comment]
https://github.com/memex-explorer/GeoParser/commit/39189c783649b130c862e02d3d59e95a44ef4eca

**Comment by MBoustani** [comment]
@smadha @chrismattmann @AravindRam

Can you please try docker installation (instruction in Readme) and let me know if there is any issue?

**Comment by AravindRam** [comment]
Hey @MBoustani 

I tried the installation through docker and worked fine. Apart from few warnings, did not face any issues during the steps of installation.
