### ISSUE TITLE
Indexed Data is not visible on Map

### ISSUE THREAD

**Issue by adityardesai** [memex-explorer/GeoParser#58]
Hi Team

We are using the GeoParser to visualize the location related details on map UI. Here is the setup and procedure we are following
1. Using Apache SOLR 4.10 as independent indexing engine under /home/user-name/src/solr
2. I have my Tika, Lucene Gazzetter and Geo parser installed in /home/user-name/src in a respective folders. 
3. I have started tika server, lucene server and Django in individual tabs on terminals. I have tested that lucene is working independently fine and also tika.
4. I have started my GeoParser Solr(5.x) on port 8983 and independent Solr(4.10) on port 8984. 

Procedure
1. I have indexed my JSON data to Solr 4.10 and its Success. Sample of the JSON is given as well. 
2. Using the steps mentioned in - https://github.com/MBoustani/GeoParser/wiki/Steps-for-geoparsing-a-Index I have Geoparsed. 
3. I get the message as Success- "Successfully Geotagged index"
4. When I select the suitable domain and click on ''View" , I see no location being rendered on the map and an error message is displayed. 

Why is GeoParser reporting it as success initially and later not able to retrieve the same data on map?
What is the expected format required. Our understanding as per https://github.com/MBoustani/GeoParser/wiki is that, the Indexed data what we provide to GeoParser will be transformed to a string and this string will be used internally by the Solr and GeoParser to plot the locations on map. Is our understanding correct?

The sample JSON file that is indexed in Apache Solr 4.10

{
"id" : "polaruscedu2M4",
"Geographic_LONGITUDE" : "77.2289700",
"Keyword" : "polaruscedu2Mz",
"Geographic_NAME" : "Delhi",
"Geographic_LATITUDE" : "28.6538100",
"Geographic_ALTITUDE" : "0.0"
}

Error logs seen on console - attached as text file
Success and Error messages  - attached as image files

Can anyone let us know why the GeoParser is behaving in this manner? 
[Error_Console.txt](https://github.com/MBoustani/GeoParser/files/194830/Error_Console.txt)
![success](https://cloud.githubusercontent.com/assets/1384924/14131989/770f093e-f5f5-11e5-8e41-780b2f4e6e16.png)
![viewerror1](https://cloud.githubusercontent.com/assets/1384924/14131990/770f4e1c-f5f5-11e5-9b91-d20b97df2b9c.png)

**Comment by smadha** [comment]
I see below stack trace which tells me that GeoParser is pointing to solr at 8984 which is same as index you are trying to geotag. Have you changed config.txt?

`http://localhost:8984/solr/admin/cores?action=CREATE&name=Delhi_1&instanceDir=Delhi_1 ERROR: Error CREATEing SolrCore 'Delhi_1': Unable to create core [Delhi_1] ...`

Please take a look at #59 may be both of you have same issue. 

@jung-jung-yeh Is your issue similar?

Also for future please consider using pastebin.com for sharing stacktrace.

**Comment by jung-jung-yeh** [comment]
No, we have different issues, we run three version of solr in different ports, and it seems memex GeoParser got the wrong solr in when doing solr commands, from my understanding, memex will use 8989 port by default, but when i print the different parameters in solr_admin.py, it access port 8984 to access admin and updated_files domain, and it results in my failure to load an index from web UI. 

We also have problems to see the geo locations, it always say no points found, can you tell us which keyword you use to feed into geoTopicParser?

http://localhost:8983/solr/test3_1/select?q=-points%3A%22%5B%5D%22&fl=points,id&wt=json&start=0&rows=50000
Traceback (most recent call last):
  File "/home/599/hw2/GeoParser/geoparser_app/solr.py", line 322, in QueryPointsIndex
    if len(response['response']['docs']) == 0:
KeyError: 'response'

'response'

---

one of our json file is:
{
        "id":"5",
        "doi": "doi:tjfyr",
        "shorturl": "http://polar.usc.edu/tjfyr",
        "title": "[DORISreport] No 0210 : IGN/JPL DORIS Report for week 1314 = 05072",
        "url": "http://polar.usc.edu/data_xhtml/message/rfc822/48FA2CCF1625817D62D3B2D6FF3DAF4AC86420911388ED61742F9AAB8E905989.xhtml",
        "Geographic_LATITUDE":"44.03459","Geographic_LONGITUDE":"-94.06703",
        "Geographic_NAME":"France",
        "text":"Pasadena"
    },
    {
        "id":"6",
        "doi": "doi:ru20p",
        "shorturl": "http://polar.usc.edu/ru20p",
        "title": "[DORISreport] No 0303 : resubmitting several DORIS weekly solutions / see DORISMail #0394",
        "url": "http://polar.usc.edu/data_xhtml/message/rfc822/EFB6210CEABB2BD81D56B87425B7F6F14117C373438445EE28E2C40EA854C95C.xhtml",
        "Geographic_LATITUDE":"37.25022","Geographic_LONGITUDE":"-119.75126","Geographic_NAME":"China",
        "text":"South Africa"
    },
    {
        "id":"7",
        "doi": "doi:zqb60",
        "shorturl": "http://polar.usc.edu/zqb60",
        "title": "http://polar.usc.edu/data_xhtml/message/rfc822/FD65FFB1A3C8CE5185EEBB70DE5846BEF4EADAEF0C2C8FCCF99031025A3A969A.xhtml",
        "url": "http://polar.usc.edu/data_xhtml/message/rfc822/FD65FFB1A3C8CE5185EEBB70DE5846BEF4EADAEF0C2C8FCCF99031025A3A969A.xhtml",
        "Geographic_LATITUDE":"62.8","Geographic_LONGITUDE":"34.8","Geographic_NAME":"Canada",
        "text":"Japan"
    },
    {
        "id":"8",
        "doi": "doi:3fetn",
        "shorturl": "http://polar.usc.edu/3fetn",
        "title": "IGSMAIL-5938: SOPAC archive problems",
        "url": "http://polar.usc.edu/data_xhtml/message/rfc822/999D927BA9282EAA82B3ED13577B615767E3B05AAB83F8F2DF55E6593C9DB45B.xhtml",
        "Geographic_NAME":"USA"
    }

**Comment by smadha** [comment]
@jung-jung-yeh Solr port and Solr URL used to store results of geo parsing are configured at two places in config.txt [L8](https://github.com/MBoustani/GeoParser/blob/master/config.txt#L8) [L7](https://github.com/MBoustani/GeoParser/blob/master/config.txt#L7)

Can you see if you have different ports here?

**Comment by smadha** [comment]
@adityardesai issues are now resolved.

**Comment by adityardesai** [comment]
Hello 

The issues is now resolved. The steps provided in wiki are really helpful, especially running tika server.  Apache Tika is very much required here and I was not using it correctly on the given port. 

Thanks @smadha for your inputs. 
![1](https://cloud.githubusercontent.com/assets/1384924/14164029/8b93c442-f6b0-11e5-8dc9-aefeea321beb.png)

Closing this issue.
