### ISSUE TITLE
Loading Solr index to GeoParser

### ISSUE THREAD

**Issue by jung-jung-yeh** [memex-explorer/GeoParser#59]
We are trying to pass an indexed data to GeoParser through the GeoParser webpage, 

However, we got the following errors from server log

[30/Mar/2016 07:53:37] "GET /return_points_khooshe/http://25.150.29.198:8984/solr/ HTTP/1.1" 500 13158
Internal Server Error: /return_points_khooshe/http://25.150.29.198:8984/solr/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/home/599/hw2/GeoParser/geoparser_app/views.py", line 210, in return_points_khooshe
    results["rows_processed"] = GetIndexSize(core_name)
  File "/home/599/hw2/GeoParser/geoparser_app/solr.py", line 300, in GetIndexSize
    rows_processed = requests.get(url, headers=headers).json()['response']['numFound']
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 763, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
**ValueError: No JSON object could be decoded
[30/Mar/2016 07:53:39] "GET /return_points_khooshe/http://25.150.29.198:8984/solr/ HTTP/1.1" 500 13158**

Could you please help us how to successfully pass our indexed core to GeoParser? Thanks!
Solr 5.3 used by GeoParser runs on port 8983

and Solr 4.10 is running on port 8984 contained our indexed core.

25.150.29.198 is virtual IP so you won't be able to access it :( 

thanks!

![2016-03-30 12 50 23](https://cloud.githubusercontent.com/assets/10208592/14135324/b3c016c2-f611-11e5-84bf-683428fb77d4.png)
![2016-03-30 12 50 02](https://cloud.githubusercontent.com/assets/10208592/14135323/b3bfbbc8-f611-11e5-9815-043190bab589.png)

**Comment by smadha** [comment]
Hi @jung-jung-yeh ,
Can you please tell if there is geo parsed data stored at `http://localhost:8983/solr/#/` with core as `test1_*` \* should be 1 ??

Also you might want to debug at `geoparser_app/solr.py, line 300` to see what is getting returned from `requests.get(url, headers=headers)` 

Thanks

**Comment by jung-jung-yeh** [comment]
Hi Madhav,

 We tried again with the wiki page https://github.com/MBoustani/GeoParser/wiki/Steps-for-geoparsing-a-Index, with our newly indexed data.
we checked the response is 

[30/Mar/2016 23:02:32] "GET /return_points_khooshe/http://25.150.29.198:8985/solr/solr/test_domain HTTP/1.1" 500 12821
{"responseHeader":{"status":400,"QTime":1},"error":{"msg":"Exception writing document id test_domain to the index; possible analysis error.","code":400}}
Internal Server Error: /query_crawled_index/http://25.150.29.198:8985/solr/solr/test_domain/user/pass

Is this issue related to localhost? We run our program on a linux server, and we use our computer to browse MEMEX GeoParser through IP instead of localhost, will it be a problem?

Will you have time today at school so we could maybe debug this together? 
Thanks
![2016-03-30 4 02 34](https://cloud.githubusercontent.com/assets/10208592/14160377/dc1c26cc-f690-11e5-8d0d-15718ce31bdf.png)
![2016-03-30 4 02 07](https://cloud.githubusercontent.com/assets/10208592/14160376/dc1ba490-f690-11e5-8544-d2e9707c5ec7.png)

**Comment by smadha** [comment]
Ok so I didn't noticed that you deployed on remote machine.
- If you open below URL in separate window you will see the issue. This is the API  geoparser calls from front end.
  `http://25.150.29.198/query_crawled_index/http://25.150.29.198:8985/solr/solr/test_domain/user/pass`
- Your core name is "solr"? Can you try opening below URL using curl command from machine you have deployed. This will ensure that geoparser can query your index.
  `http://25.150.29.198:8985/solr/solr/select?q=*&rows=1`
- Please ensure that your tika server is running on port: 8001 (unless you have changed it in config.txt) and test it separately as mentioned in [https://wiki.apache.org/tika/GeoTopicParser](https://wiki.apache.org/tika/GeoTopicParser). `curl -T $HOME/src/geotopicparser-utils/geotopics/polar.geot -H "Content-Disposition: attachment; filename=polar.geot" http://localhost:8001/rmeta` This was the issue for some of the people.
- Please share server logs using pastebin for API - query_crawled_index

You can ping me on  hangouts - msharan@usc.edu. Also @antrromet and @adityardesai have successfully installed GeoParser from your course in case they can help

**Comment by jung-jung-yeh** [comment]
we finally loaded the data and see the visualization! thanks for the help! the explanation is very nice
