### ISSUE TITLE
Map doesn't load in safari on Mac OS

### ISSUE THREAD

**Issue by rrgirish** [memex-explorer/GeoParser#63]
Hi,

I tried running this on safari in Mac OS and I am not seeing the map load in the background on the canvas. 

It works fine on chrome.

Screenshot attached. You can see the points being displayed in the red circles. There is no map behind the dots :)

<img width="1236" alt="screen shot 2016-04-02 at 3 36 58 pm" src="https://cloud.githubusercontent.com/assets/6744183/14229447/0ce4a59a-f8e9-11e5-87c9-2f0420519b7c.png">

Regards
Girish

**Comment by smadha** [comment]
Thanks for sharing. If you can submit a PR that would be awesome. 

We will fix it soon anyway :+1:

**Comment by smadha** [comment]
Fixed with #65 

Safari was somehow not supporting subdomain with braces '{s}'

@rrgirish can you confirm this on your system?

**Comment by rrgirish** [comment]
Confirmed this works now. Thanks!

Regards
Girish
