### ISSUE TITLE
GeoParser throws the following error when run.

### ISSUE THREAD

**Issue by hasanayesha** [memex-explorer/GeoParser#67]
Hi,

I get the following error when trying to run GeoParser.
<img width="717" alt="screen shot 2016-04-03 at 11 41 29 pm" src="https://cloud.githubusercontent.com/assets/3942110/14239975/d980838c-f9f5-11e5-9d6e-fbc1528846ad.png">

 Can you please tell me what the problem is.

**Comment by smadha** [comment]
Can't figure out much from these logs. Can you share full console preferably via pastebin.com?

You can also open this URL in your browser to reproduce the error -
`localhost:8000/query_crawled_index/http://localhost:8984/solr/polrsolr/test/user/pass`

Also can you please ensure that tika server is running fine on 8001 port and you can see proper results WITH GEOLOCATIONS as mentioned in [https://wiki.apache.org/tika/GeoTopicParser](https://wiki.apache.org/tika/GeoTopicParser)

`curl -T $HOME/src/geotopicparser-utils/geotopics/polar.geot -H "Content-Disposition: attachment; filename=polar.geot" http://localhost:8001/rmeta` 

This was the issue for some of the people.

**Comment by hasanayesha** [comment]
I can see the proper results when i run tika server on port 8001. 
The admin core is created when GeoParser is run the first time. But this error is thrown later on.

These are the two get requests which throw an error.
*\* 04/Apr/2016 06:50:31] "GET /return_points_khooshe/http://localhost:8984/solr/polrsolr/test HTTP/1.1" 500 13794
*\* [04/Apr/2016 08:06:14] "GET /list_of_domains/ HTTP/1.1" 500 13506

The results of the reproduced error are:

ScannerError at /query_crawled_index/http://localhost:8984/solr/polrsolr/test/user/pass
mapping values are not allowed here
  in "<unicode string>", line 7, column 48:
     ... ssing /solr/admin/select. Reason:
                                         ^
Request Method: GET
Request URL:    http://localhost:8000/query_crawled_index/http://localhost:8984/solr/polrsolr/test/user/pass
Django Version: 1.8.5
Exception Type: ScannerError
Exception Value:  
mapping values are not allowed here
  in "<unicode string>", line 7, column 48:
     ... ssing /solr/admin/select. Reason:
                                         ^
Exception Location: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/scanner.py in fetch_value, line 580
Python Executable:  /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Python Version: 2.7.9
Python Path:  
['/Users/ayesh/Desktop/ContentDetection/Assignment2/Antro-Geo/GeoParser',
 '/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7',
 '/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7/site-packages',
 '/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-14.0-py2.7.egg',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/beautifulsoup4-4.3.2-py2.7.egg',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/py4j-0.9-py2.7.egg',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-2.48.0-py2.7.egg',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/solrpy-0.9.7-py2.7.egg',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/CherryPy-3.8.0-py2.7.egg',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/carton-0.3-py2.7.egg',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages',
 '/Library/Python/2.7/site-packages']
Server time:    Mon, 4 Apr 2016 08:06:37 +0000
Traceback Switch to copy-and-paste view

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py in get_response
                                response = wrapped_callback(request, _callback_args, *_callback_kwargs) ...
▶ Local vars
/Users/ayesh/Desktop/ContentDetection/Assignment2/Antro-Geo/GeoParser/geoparser_app/views.py in query_crawled_index
                    core_name = get_index_core(domain_name, indexed_path) ...
▶ Local vars
/Users/ayesh/Desktop/ContentDetection/Assignment2/Antro-Geo/GeoParser/geoparser_app/solr_admin.py in get_index_core
                    response = _get_domain_admin(domain) ...
▶ Local vars
/Users/ayesh/Desktop/ContentDetection/Assignment2/Antro-Geo/GeoParser/geoparser_app/solr_admin.py in _get_domain_admin
                return yaml.safe_load(response.text) ...
▶ Local vars
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/__init__.py in safe_load
                return load(stream, SafeLoader) ...
▶ Local vars
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/**init**.py in load
                    return loader.get_single_data() ...
▶ Local vars
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/constructor.py in get_single_data
                    node = self.get_single_node() ...
▶ Local vars
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/composer.py in get_single_node
                        document = self.compose_document() ...
▶ Local vars
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/composer.py in compose_document
                    self.get_event() ...
▶ Local vars
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/parser.py in get_event
                            self.current_event = self.state() ...
▶ Local vars
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/parser.py in parse_document_end
                    token = self.peek_token() ...
▶ Local vars
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/scanner.py in peek_token
                        self.fetch_more_tokens() ...
▶ Local vars
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/scanner.py in fetch_more_tokens
                        return self.fetch_value() ...
▶ Local vars
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yaml/scanner.py in fetch_value
                                        self.get_mark()) ...
▶ Local vars
Request information

GET
No GET data
POST
No POST data
FILES
No FILES data
COOKIES
Variable    Value
csrftoken  
'eyOYtzfUEr7pmwxBltFcuORQhPNXQndp'
META
Variable    Value
RUN_MAIN  
'true'
HTTP_COOKIE 
'csrftoken=eyOYtzfUEr7pmwxBltFcuORQhPNXQndp'
SERVER_PROTOCOL 
'HTTP/1.1'
SERVER_SOFTWARE 
'WSGIServer/0.1 Python/2.7.9'
TERM_PROGRAM_VERSION  
'361.1'
REQUEST_METHOD  
'GET'
LOGNAME 
'ayesh'
USER  
'ayesh'
PATH  
'/opt/local/bin:/opt/local/sbin:/Users/ayesh/anaconda/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ayesh/Desktop/ContentDetection/Assignment2/lucene-geo-gazetteer/src/main/bin:/opt/X11/bin'
QUERY_STRING  
''
HOME  
'/Users/ayesh'
DISPLAY 
'/private/tmp/com.apple.launchd.m0JJL7HC7a/org.macosforge.xquartz:0'
TERM_PROGRAM  
'Apple_Terminal'
LANG  
'en_US.UTF-8'
TERM  
'xterm-256color'
SHELL  
'/bin/bash'
TZ  
'UTC'
SERVER_NAME 
'1.0.0.127.in-addr.arpa'
REMOTE_ADDR 
'127.0.0.1'
SHLVL  
'1'
XPC_FLAGS  
'0x0'
wsgi.url_scheme 
'http'
_  
'/Library/Frameworks/Python.framework/Versions/2.7/bin/python'
SERVER_PORT 
'8000'
JAVA_HOME  
'/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home'
CONTENT_LENGTH  
''
TERM_SESSION_ID 
'342C07ED-CB69-4A6A-A6D6-FAE2C5CF9815'
XPC_SERVICE_NAME  
'0'
SSH_AUTH_SOCK  
'/private/tmp/com.apple.launchd.dtZZUc82wm/Listeners'
HTTP_CONNECTION 
'keep-alive'
wsgi.input  
<socket._fileobject object at 0x106209f50>
Apple_PubSub_Socket_Render  
'/private/tmp/com.apple.launchd.Ktm6Fk8Wnv/Render'
HTTP_HOST  
'localhost:8000'
SCRIPT_NAME 
u''
wsgi.multithread  
True
HTTP_UPGRADE_INSECURE_REQUESTS  
'1'
TMPDIR  
'/var/folders/2b/_vsz_s1n3195n8pjsjsfv0bm0000gn/T/'
HTTP_ACCEPT 
'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8'
wsgi.version  
(1, 0)
HTTP_USER_AGENT 
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36'
GATEWAY_INTERFACE  
'CGI/1.1'
wsgi.run_once  
False
CSRF_COOKIE 
u'eyOYtzfUEr7pmwxBltFcuORQhPNXQndp'
OLDPWD  
'/Users/ayesh/Desktop/ContentDetection/Assignment2/Antro-Geo/GeoParser/Solr'
wsgi.multiprocess  
False
HTTP_ACCEPT_LANGUAGE  
'en-US,en;q=0.8'
wsgi.errors 
<open file '<stderr>', mode 'w' at 0x1002931e0>
__CF_USER_TEXT_ENCODING 
'0x1F5:0x0:0x0'
PWD 
'/Users/ayesh/Desktop/ContentDetection/Assignment2/Antro-Geo/GeoParser'
HTTP_DNT  
'1'
DJANGO_SETTINGS_MODULE  
'geoparser.settings'
CONTENT_TYPE  
'text/plain'
wsgi.file_wrapper  
''
REMOTE_HOST 
''
HTTP_ACCEPT_ENCODING  
'gzip, deflate, sdch'
PATH_INFO  
u'/query_crawled_index/http://localhost:8984/solr/polrsolr/test/user/pass'
Settings
Using settings module geoparser.settings
Setting Value
SECURE_BROWSER_XSS_FILTER  
False
USE_THOUSAND_SEPARATOR  
False
CSRF_COOKIE_SECURE  
False
LANGUAGE_CODE  
'en-us'
ROOT_URLCONF  
'geoparser.urls'
MANAGERS  
()
BASE_DIR  
'/Users/ayesh/Desktop/ContentDetection/Assignment2/Antro-Geo/GeoParser'
SILENCED_SYSTEM_CHECKS  
[]
DEFAULT_CHARSET 
'utf-8'
SESSION_SERIALIZER  
'django.contrib.sessions.serializers.JSONSerializer'
STATIC_ROOT 
None
ALLOWED_HOSTS  
[]
MESSAGE_STORAGE 
'django.contrib.messages.storage.fallback.FallbackStorage'
EMAIL_SUBJECT_PREFIX  
'[Django] '
SERVER_EMAIL  
'root@localhost'
SECURE_HSTS_SECONDS 
0
STATICFILES_FINDERS 
('django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder')
SESSION_CACHE_ALIAS 
'default'
SESSION_COOKIE_DOMAIN  
None
SESSION_COOKIE_NAME 
'sessionid'
TIME_INPUT_FORMATS  
('%H:%M:%S', '%H:%M:%S.%f', '%H:%M')
SECURE_REDIRECT_EXEMPT  
[]
DATABASES  
{'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_MAX_AGE': 0,
             'ENGINE': 'django.db.backends.sqlite3',
             'HOST': '',
             'NAME': '/Users/ayesh/Desktop/ContentDetection/Assignment2/Antro-Geo/GeoParser/db.sqlite3',
             'OPTIONS': {},
             'PASSWORD': u'*******************_',
             'PORT': '',
             'TEST': {'CHARSET': None,
                      'COLLATION': None,
                      'MIRROR': None,
                      'NAME': None},
             'TIME_ZONE': 'UTC',
             'USER': ''}}
EMAIL_SSL_KEYFILE  
u'**_****************_'
FILE_UPLOAD_DIRECTORY_PERMISSIONS  
None
FILE_UPLOAD_PERMISSIONS 
None
FILE_UPLOAD_HANDLERS  
('django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler')
DEFAULT_CONTENT_TYPE  
'text/html'
APPEND_SLASH  
True
LOCALE_PATHS  
()
DATABASE_ROUTERS  
[]
DEFAULT_TABLESPACE  
''
YEAR_MONTH_FORMAT  
'F Y'
STATICFILES_STORAGE 
'django.contrib.staticfiles.storage.StaticFilesStorage'
CACHES  
{'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
SESSION_COOKIE_PATH 
'/'
SECURE_CONTENT_TYPE_NOSNIFF 
False
MIDDLEWARE_CLASSES  
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')
USE_I18N  
True
THOUSAND_SEPARATOR  
','
SECRET_KEY  
u'**_****************_'
LANGUAGE_COOKIE_NAME  
'django_language'
DEFAULT_INDEX_TABLESPACE  
''
LOGGING_CONFIG  
'logging.config.dictConfig'
TEMPLATE_LOADERS  
('django.template.loaders.filesystem.Loader',
 'django.template.loaders.app_directories.Loader')
FIRST_DAY_OF_WEEK  
0
WSGI_APPLICATION  
'geoparser.wsgi.application'
TEMPLATE_DEBUG  
False
X_FRAME_OPTIONS 
'SAMEORIGIN'
CSRF_COOKIE_NAME  
'csrftoken'
FORCE_SCRIPT_NAME  
None
USE_X_FORWARDED_HOST  
False
EMAIL_TIMEOUT  
None
SECURE_SSL_HOST 
None
SIGNING_BACKEND 
'django.core.signing.TimestampSigner'
SESSION_COOKIE_SECURE  
False
CSRF_COOKIE_DOMAIN  
None
FILE_CHARSET  
'utf-8'
DEBUG  
True
LANGUAGE_COOKIE_DOMAIN  
None
DEFAULT_FILE_STORAGE  
'django.core.files.storage.FileSystemStorage'
INSTALLED_APPS  
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'geoparser_app')
LANGUAGES  
(('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('ast', 'Asturian'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-au', 'Australian English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy', 'Frisian'),
 ('ga', 'Irish'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hu', 'Hungarian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('io', 'Ido'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('mr', 'Marathi'),
 ('my', 'Burmese'),
 ('nb', 'Norwegian Bokmal'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('os', 'Ossetic'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('th', 'Thai'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('vi', 'Vietnamese'),
 ('zh-cn', 'Simplified Chinese'),
 ('zh-hans', 'Simplified Chinese'),
 ('zh-hant', 'Traditional Chinese'),
 ('zh-tw', 'Traditional Chinese'))
USE_L10N  
True
SECURE_HSTS_INCLUDE_SUBDOMAINS  
False
STATICFILES_DIRS  
()
PREPEND_WWW 
False
SECURE_PROXY_SSL_HEADER 
None
LANGUAGE_COOKIE_AGE 
None
SESSION_COOKIE_HTTPONLY 
True
DEBUG_PROPAGATE_EXCEPTIONS  
False
CSRF_COOKIE_AGE 
31449600
MONTH_DAY_FORMAT  
'F j'
LOGIN_URL  
'/accounts/login/'
SESSION_EXPIRE_AT_BROWSER_CLOSE 
False
TIME_FORMAT 
'P'
AUTH_USER_MODEL 
'auth.User'
DATE_INPUT_FORMATS  
('%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y')
AUTHENTICATION_BACKENDS 
('django.contrib.auth.backends.ModelBackend',)
EMAIL_HOST_PASSWORD 
u'**_****************_'
PASSWORD_RESET_TIMEOUT_DAYS 
u'**_****************_'
SESSION_FILE_PATH  
None
CACHE_MIDDLEWARE_ALIAS  
'default'
SESSION_SAVE_EVERY_REQUEST  
False
NUMBER_GROUPING 
0
SESSION_ENGINE  
'django.contrib.sessions.backends.db'
CSRF_FAILURE_VIEW  
'django.views.csrf.csrf_failure'
CSRF_COOKIE_PATH  
'/'
LOGIN_REDIRECT_URL  
'/accounts/profile/'
DECIMAL_SEPARATOR  
'.'
IGNORABLE_404_URLS  
()
MIGRATION_MODULES  
{}
TEMPLATE_STRING_IF_INVALID  
''
LOGOUT_URL  
'/accounts/logout/'
EMAIL_USE_TLS  
False
FIXTURE_DIRS  
()
EMAIL_HOST  
'localhost'
DATE_FORMAT 
'N j, Y'
MEDIA_ROOT  
''
DEFAULT_EXCEPTION_REPORTER_FILTER  
'django.views.debug.SafeExceptionReporterFilter'
ADMINS  
()
FORMAT_MODULE_PATH  
None
DEFAULT_FROM_EMAIL  
'webmaster@localhost'
MEDIA_URL  
''
DATETIME_FORMAT 
'N j, Y, P'
TEMPLATE_DIRS  
()
DISALLOWED_USER_AGENTS  
()
ALLOWED_INCLUDE_ROOTS  
()
LOGGING 
{}
SHORT_DATE_FORMAT  
'm/d/Y'
TEMPLATES  
[{'APP_DIRS': True,
  'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'DIRS': ['/Users/ayesh/Desktop/ContentDetection/Assignment2/Antro-Geo/GeoParser/geoparser_app/templates'],
  'OPTIONS': {'context_processors': ['django.template.context_processors.debug',
                                     'django.template.context_processors.request',
                                     'django.contrib.auth.context_processors.auth',
                                     'django.contrib.messages.context_processors.messages']}}]
TEST_RUNNER 
'django.test.runner.DiscoverRunner'
CACHE_MIDDLEWARE_KEY_PREFIX 
u'**_****************_'
SECURE_SSL_REDIRECT 
False
TIME_ZONE  
'UTC'
FILE_UPLOAD_MAX_MEMORY_SIZE 
2621440
EMAIL_BACKEND  
'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_SSL  
False
TEMPLATE_CONTEXT_PROCESSORS 
('django.contrib.auth.context_processors.auth',
 'django.template.context_processors.debug',
 'django.template.context_processors.i18n',
 'django.template.context_processors.media',
 'django.template.context_processors.static',
 'django.template.context_processors.tz',
 'django.contrib.messages.context_processors.messages')
SESSION_COOKIE_AGE  
1209600
SETTINGS_MODULE 
'geoparser.settings'
USE_ETAGS  
False
LANGUAGES_BIDI  
('he', 'ar', 'fa', 'ur')
FILE_UPLOAD_TEMP_DIR  
None
INTERNAL_IPS  
()
STATIC_URL  
'/static/'
EMAIL_PORT  
25
USE_TZ  
True
SHORT_DATETIME_FORMAT  
'm/d/Y P'
TEST_NON_SERIALIZED_APPS  
[]
PASSWORD_HASHERS  
u'**_*****************'
ABSOLUTE_URL_OVERRIDES  
{}
LANGUAGE_COOKIE_PATH  
'/'
CACHE_MIDDLEWARE_SECONDS  
600
EMAIL_SSL_CERTFILE  
None
CSRF_COOKIE_HTTPONLY  
False
DATETIME_INPUT_FORMATS  
('%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y')
EMAIL_HOST_USER 
''
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code.

**Comment by smadha** [comment]
Well by looking at logs it seems issue is with querying solr core in
solr_admin.py.

Can you confirm if you are able to query admin core from browser -

`http://localhost:8983/solr/admin/select?q=*:*&wt=json`
- Can you try restarting your solr provided within GeoParser?
- Try printing response variable on line
  https://github.com/MBoustani/GeoParser/blob/master/geoparser_app/solr_admin.py#L28

may be we can do a screenshare on hangouts to debug the issue if it does
not resolves your problem.

## 

Madhav Sharan

**Comment by hasanayesha** [comment]
Turns out the error was in my solr core. I can run Geoparser now. Thanks!
