### ISSUE TITLE
Discussion about Search functionality

### ISSUE THREAD

**Issue by antrromet** [memex-explorer/GeoParser#68]
@chrismattmann @MBoustani @smadha 
I've added pagination in the search results.
We will have to figure out a way as to what fields should be displayed in the search query. As of now its hardcoded to look for `title` or `dc-title`. If those are not present then `No Title` will be shown.
<img width="1280" alt="screen shot 2016-04-05 at 1 12 14 am" src="https://cloud.githubusercontent.com/assets/1651551/14275559/e42b5578-facc-11e5-87d8-dff6c9a97ca4.png">
Lemme know what you guys think.

**Comment by MBoustani** [comment]
@antrromet looks great, can you put an transparent background under search result?

**Comment by smadha** [comment]
@antrromet Does search function displays anything on map?

**Comment by antrromet** [comment]
@smadha Not as of now. But of course we would have to add that functionality.

**Comment by smadha** [comment]
:+1: 
This is the initial mockup that @lawongsta prepared for all the functionalities. Things have changed a bit but it should give a good idea of workflow.

https://drive.google.com/file/d/0B8s73OrIJNwjQ3pNNXBjbm05OUU/view?usp=sharing

**Comment by antrromet** [comment]
@MBoustani This is how it looks now.

<img width="1280" alt="screen shot 2016-04-06 at 12 24 50 am" src="https://cloud.githubusercontent.com/assets/1651551/14309090/f754eea8-fb8e-11e5-959d-6d21adf53060.png">

@smadha Thanks for that doc, its really useful. I've made some minor UI modifications based on that. We should discuss about how we would display the results on the map.

**Comment by smadha** [comment]
Sure, I will schedule a hangout between all of us.
@MBoustani @chrismattmann

**Comment by MBoustani** [comment]
@antrromet looks great. Can you send the PR for new UI changes?

**Comment by smadha** [comment]
@MBoustani We are working on new branch "search" for this

**Comment by antrromet** [comment]
@chrismattmann 
@smadha @MBoustani and I just had a call regarding the Search functionality and we reached the following consensus.
When the user types in any keyword to search, we would search the remote Solr for the results. Then whatever results are fetched, we would check its intersection with our local Solr (this has all the docs with geolocations). And these are the results that would be shown on Khooshe map.
For instance, if you search for Ak47 and you got 10k results from the remote Solr, but out of those only say 5k had gelocations associated with them, then we would display those 5k results on the map, and the user would be able to hover over the points and then exactly similar functionality as in Viewing of points.
We would change the UI to remove the pagination, and list of results. Would only be displaying the Khooshe points as of now.

**Comment by MBoustani** [comment]
@antrromet we are breaking the remaining of task to new two smaller issues:
https://github.com/MBoustani/GeoParser/issues/74
https://github.com/MBoustani/GeoParser/issues/75
