### ISSUE TITLE
Default view when user launches GeoParser for the first time

### ISSUE THREAD

**Issue by antrromet** [memex-explorer/GeoParser#69]
We need to have some kind of a default view (a default index) thats loaded into Geoparser, so that the user sees some points on the map, the first time GeoParser is launched. This is good suggestion, because as of now it looks too blank and it would also give the user a look and feel as to how GeoParser is gonna work like.

**Comment by smadha** [comment]
I can take care of this. I think we should have some query parameters in URL which will connect to view index. So URL should look like `localhost:8000/viewIndex?indexPath=http://path/to/polar/index&domain=polar`

As of now it will show all the geo parsed data for uploaded files.

Thanks for creating this issue.

**Comment by smadha** [comment]
Added deep linking functionality. 

We can now create deep links to view a particular index. Example below -

http://localhost:8000/?idx=http://localhost:8983/solr/core1&domain=test&v=i
1. v --view  values => {i —index , f —file , s —search}
2. idx -- index path
3. domain -- name of domain
