### ISSUE TITLE
Automated discovery of Index type

### ISSUE THREAD

**Issue by aalavandhan** [memex-explorer/GeoParser#70]
As per @MBoustani's suggestions.

1) The user's interaction should be limited to pasting a URL.
2) The application should implement a 'smart'  mechanism to determine the type of index.
3) Possibly make API calls to certain endpoints to determine the index type based on the response.

(eg) Making a get request to http://localhost:9200 [ Elastic search ] will return the following JSON which might be an indicator that the given index is an elastic search index.

``` JSON
{
  "name": "mm",
  "cluster_name": "meta-magic",
  "version": {
    "number": "2.2.1",
    "build_hash": "d045fc29d1932bce18b2e65ab8b297fbf6cd41a1",
    "build_timestamp": "2016-03-09T09:38:54Z",
    "build_snapshot": false,
    "lucene_version": "5.4.1"
  },
  "tagline": "You Know, for Search"
}

```

**Design considerations**:
1) Version independence
2) Robustness

**Comment by smadha** [comment]
For solr we can use ping api for a core

`http://localhost:8983/solr/new_core/admin/ping?wt=json`

```
{
    "responseHeader": {
        "QTime": 23,
        "params": {
            "df": "text",
            "distrib": "false",
            "echoParams": "all",
            "q": "solrpingquery",
            "rows": "10",
            "wt": "json"
        },
        "status": 0
    },
    "status": "OK"
}
```

I would still like to stick with a radio button to keep it simple, may be we can use this cool feature if user does not selects anything.

**Comment by aalavandhan** [comment]
@smadha +1 for the radio button
