### ISSUE TITLE
Delete tiles from search folder "geoparser_app/static/search/tiles"

### ISSUE THREAD

**Issue by smadha** [memex-explorer/GeoParser#76]
We need to think of some way to clear tiles folder as currently we create new tile folder for every search. This may cause memory issues and we might not release unused memory.

**Comment by MBoustani** [comment]
https://github.com/MBoustani/GeoParser/commit/d559370eed6fdf149005c0cbbbbd6510fd47cdd1
and
https://github.com/MBoustani/GeoParser/commit/f264b3f3c7c24911efb7d0cb1b5e3f3c261869ec
In case of removing search folders you can pass:
tiles_path = geoparser_app/static/search/tiles/
Example: http://127.0.0.1:8000/remove_khooshe_tile/geoparser_app/static/search/tiles/<folder name>
