### ISSUE TITLE
Serving cached response if results for a search response is already available.

### ISSUE THREAD

**Issue by smadha** [memex-explorer/GeoParser#77]

**Comment by MBoustani** [comment]
@smadha are we separating tasks here? Python and frontend? ;)

**Comment by smadha** [comment]
Sure! this and #76 can be put together and we can redefine as per our discussion on Lunch

**Comment by MBoustani** [comment]
https://github.com/MBoustani/GeoParser/commit/5fbfa3718aacfdfc5c4a2a73624aa17b2585613d
and 
https://github.com/MBoustani/GeoParser/commit/8cf3db1e68d4b7112c68ba37cd57b204074404d6

**Comment by smadha** [comment]
@MBoustani : I will do the front end
We will need few more API's in views.py- 
1. get list of saved searches.
2. get khooshe tile path for given saved search. (same as response for search_crawled_index)

**Comment by MBoustani** [comment]
@smadha 
1- You can get the list of searches (same as list of tiles folder return from "list_of_searched_tiles" function)
2- Khooshe tiles path for given search would be = geoparser_app/static/search/tiles/ + [search_keyword]

**Comment by smadha** [comment]
@MBoustani Just the tile path wont do. It requires full response like from "search_crawled_index"

**Comment by smadha** [comment]
something like this - [{'rows_processed': 7207971, 'points_count': 20084026, 'total_docs': 7208416, 'khooshe_tile': 'static/tiles/search/keyword', 'popup_fields': 'url,title'}]
