### ISSUE TITLE
Store encrypted username password of an index in solr admin

### ISSUE THREAD

**Issue by smadha** [memex-explorer/GeoParser#78]

**Comment by MBoustani** [comment]
@smadha are we going to encrypt the username and password on front end and pass to backend, or encode in python side before store in Solr?
I think encoding in front end using JavaScript would be better option.

**Comment by smadha** [comment]
hmm.. I think we should encrypt/decrypt on server side. We should create a secret key and store it on our server.

What say? @MBoustani

**Comment by MBoustani** [comment]
Yeah seems like is better to encrypt/decrypt on server side.
https://www.stackfield.com/blog/cloud-encryption---client-side-vs-server-side-1

https://github.com/andrewcooke/simple-crypt

**Comment by smadha** [comment]
@MBoustani simple-crypt was very slow. I ended up using https://github.com/google/keyczar it's also recomended by simple-crypt

@chrismattmann
