### ISSUE TITLE
Create a link from pop-ups to FacetView

### ISSUE THREAD

**Issue by MBoustani** [memex-explorer/GeoParser#81]
Create a configuration to set the link for pop-up.
For example be able to link each point to faceview item.

http://imagecat.dyndns.org/weapons/facetview/ads/.....

**Comment by MBoustani** [comment]
@chrismattmann Can you help me find a connection between Solr endpoint and FacetView url?

Here is one point Solr end point:
http://imagecat.dyndns.org/solr/imagecatdev/select?q=id:%22file:/data2/USCWeaponsStatsGathering/nutch/full_dump/org/wikipedia/en/BB34BBE4049E150C3B60445CDDC0E3BC30235883A4668DAE9AB99DF306E16604%22&wt=json&indent=true

What URL would be for FacetView?

**Comment by chrismattmann** [comment]
@khundman can you help

**Comment by khundman** [comment]
@MBoustani @chrismattmann Sorry for the delay. Mazi, this would be the facetview url: 
http://imagecat.dyndns.org/weapons/facetview/ads/index.html?query=id:%22file:/data2/USCWeaponsStatsGathering/nutch/full_dump/org/wikipedia/en/BB34BBE4049E150C3B60445CDDC0E3BC30235883A4668DAE9AB99DF306E16604%22&wt=json&indent=true
