### ISSUE TITLE
Overcome maven-enforcer-plugin issue while installing manually

### ISSUE THREAD

**Issue by AravindRam** [memex-explorer/GeoParser#84]
Hey @smadha @MBoustani 

I had come across this error last time when I installed GeoParser and even now. While trying to build the lucene-geo-gazetteer using the command "mvn install assembly:assembly", the build fails and it throws an error saying missing maven-enforcer-plugin. So, I included the following in pom.xml present inside lucene-geo-gazetteer cloned repo and commented out the plugin which is currently present in the pom.xml for enforcer-plugin.

//Commented out plugin

```
             <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-enforcer-plugin</artifactId>
            <version>1.4.1</version>
            <executions>
                <execution>
                    <id>enforce-java</id>
                    <phase>validate</phase>
                    <goals>
                        <goal>enforce</goal>
                    </goals>
                    <configuration>
                        <rules>
                            <requireJavaVersion>
                                <version>[1.7.0,1.8)</version>
                                <message>Error:: Please use jdk7 for compilation.      
                                                            </message>
                                </requireJavaVersion>
                        </rules>
                    </configuration>
                </execution>
            </executions>
     </plugin>
```

// Replaced with the following plugin

```
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-enforcer-plugin</artifactId>
            <version>1.4.1</version>
            <executions>
                <execution>
                    <id>enforce-versions</id>
                    <goals>
                        <goal>enforce</goal>
                    </goals>
                    <configuration>
                        <rules>
                            <bannedPlugins>
                                <!-- will only display a warning but does not fail the build. -->
                                <level>WARN</level>
                                <excludes>
                                    <exclude>org.apache.maven.plugins:maven-verifier-plugin</exclude>
                                </excludes>
                                <message>Please consider using the maven-invoker-plugin (http://maven.apache.org/plugins/maven-invoker-plugin/)!</message>
                            </bannedPlugins>
                            <requireMavenVersion>
                                <version>2.0.6</version>
                            </requireMavenVersion>
                            <requireJavaVersion>
                                <version>1.5</version>
                            </requireJavaVersion>
                            <requireOS>
                                <family>unix</family>
                            </requireOS>
                        </rules>
                    </configuration>
                </execution>
            </executions>
        </plugin>
```

Got the plugin from the following link

http://maven.apache.org/enforcer/maven-enforcer-plugin/usage.html

Once I made this change, the build was successful. I am documenting this so that if someone faces the same problem later on, they can make use of this to resolve this issue while installing GeoParser manually.

**Comment by smadha** [comment]
This does not seems like an issue with pom but with your maven
configuration. We use enforcer to make contributors use java 7 for
 lucene-geo-gazetteer. It will build with jdk 8 as well but the idea was
not to mandate java 8.

Did you installed enforcer plugin separately? I think it should work
automatically.

Also, Can you ensure your java version is 7 ?

## Thanks!

Madhav Sharan

**Comment by AravindRam** [comment]
@smadha 

No I did not install the enforcer plugin separately. I just replaced it with the plugin I have shared above. I don't think the issue is with the jdk since my java version is 8 only. Any other reason why this failed?

Thanks

**Comment by smadha** [comment]
Java version should be 7 not 8. That must be the error you see. As I said
before we used enforcer to make contributors use java 7 for
 lucene-geo-gazetteer. It will build with jdk 8 as well but the idea was to
not mandate java 8.

I have a cleaner solution to it but for now use java 7
